services:
  - type: web
    name: aambal-nayam
    runtime: node
    plan: free
    region: singapore
    buildCommand: rm -rf node_modules && npm install --include=dev && npm run build
    startCommand: npm run seed && npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
